/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/examples/**/*.{js,ts,jsx,tsx,mdx}",
        "./node_modules/flowbite/**/*.js",
        "./src/**/*.{html,js}",
        "./node_modules/tw-elements/dist/js/**/*.js",
        "./pages/**/*.{ts,tsx}",
        "./public/**/*.html",
    ],
    theme: {
        extend: {
            fontFamily: {
                poppins: ["var(--font-poppins)"],
                inter: ["var(--font-inter)"],
            },
            backgroundImage: {
                "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
                "gradient-conic":
                    "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
            },
            fontSize: {
                "body-1": ["10px", "14px"],
                "body-2": ["10px", "20px"],
                "body-3": ["12px", "18px"],
                "body-4": ["12px", "20px"],
                "body-5": ["14px", "18px"],
                "body-6": ["14px", "20px"],
                "title-1": ["16px", "20px"],
                "title-2": ["16px", "24px"],
                "title-3": ["18px", "26px"],
                "head-1": ["20px", "30px"],
                "head-2": ["24px", "36px"],
                "head-3": ["36px", "54px"],
            },
            colors: {
               'purple-1': '#E2D4F0',
                'purple-2': '#D0B7E6',
                'purple-3': '#A06ECE',
                'purple-4': '#7126B5',
                'purple-5': '#4B1979',
                'purple-6': '#C1BBEB',
                'cream-1': '#FFF8ED',
                'cream-2': '#FFF0DC',
                'cream-3': '#FFE9CA',
                'cream-4': '#D4C2A8',
                'cream-5': '#AA9B87',
                'neutral-1': '#FFF',
                'neutral-2': '#D0D0D0',
                'neutral-3': '#8A8A8A',
                'neutral-4': '#3C3C3C',
                'neutral-5': '#151515',
                'alert-1': '#73CA5C',
                'alert-2': '#F9CC00',
                'alert-3': '#FF0000',
                'blue-1' : '#003D20',
                'grey-1' : '#C1BBEB',
                'grey-2'  : '#F3F4FF',
            },
            boxShadow: {
                high: "0px 0px 10px rgba(0, 0, 0, 0.15)",
                low: "0px 0px 4px rgba(0, 0, 0, 0.15)",
            },
            borderRadius: {
                "rad-1": "4px",
                "rad-2": "8px",
                "rad-3": "12px",
                "rad-4": "16px",
            },
        },
    },
    plugins: [
        // require("daisyui"),
        require('flowbite/plugin'),
        // require("tw-elements/dist/plugin.cjs"),
    ],
};
